# Generated by Django 5.2.8 on 2026-08-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_shipment_status_alter_shipment_id_shipmentupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="shipmentupdate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
