# Generated by Django 5.2.8 on 2026-08-26 13:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_alter_shipment_id_alter_shipmentupdate_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="estimated_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="package_type",
            field=models.CharField(
                choices=[
                    ("Document", "Document"),
                    ("Electronics", "Electronics"),
                    ("Clothing", "Clothing"),
                    ("Food", "Food"),
                    ("Fragile", "Fragile"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Standard", "Standard"),
                    ("Express", "Express"),
                    ("Urgent", "Urgent"),
                ],
                default="Standard",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=10
            ),
        ),
    ]
