# Generated by Django 5.2.8 on 2026-08-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_shipment_estimated_delivery_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentupdate",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipmentupdate",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
